/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author caua
 */
public class ViewMenu extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenu
     */
    public ViewMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        lblFundo1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuClientes = new javax.swing.JMenu();
        itmConsultarClientes = new javax.swing.JMenuItem();
        itmAlterarClientes = new javax.swing.JMenuItem();
        itmCancelarClientes = new javax.swing.JMenuItem();
        itmRelatóriosClientes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itmPagamentoClientes = new javax.swing.JMenuItem();
        mnuFuncionários = new javax.swing.JMenu();
        itmCadastrarFuncionario = new javax.swing.JMenuItem();
        itmConsultarFuncionario = new javax.swing.JMenuItem();
        itmAlterarFuncionario = new javax.swing.JMenuItem();
        itmExcluirFuncionario = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Funcionários");
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image-removebg-preview_4.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 60, 390, 230);

        lblFundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image.png"))); // NOI18N
        getContentPane().add(lblFundo1);
        lblFundo1.setBounds(-10, 0, 680, 370);

        mnuClientes.setBorder(null);
        mnuClientes.setText("Clientes");

        itmConsultarClientes.setText("Consultar Pedidos");
        itmConsultarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmConsultarClientesActionPerformed(evt);
            }
        });
        mnuClientes.add(itmConsultarClientes);

        itmAlterarClientes.setText("Alterar Pedidos");
        mnuClientes.add(itmAlterarClientes);

        itmCancelarClientes.setText("Cancelar Pedidos");
        mnuClientes.add(itmCancelarClientes);

        itmRelatóriosClientes.setText("Relatórios ");
        mnuClientes.add(itmRelatóriosClientes);
        mnuClientes.add(jSeparator1);

        itmPagamentoClientes.setText("Pagamento");
        mnuClientes.add(itmPagamentoClientes);

        jMenuBar1.add(mnuClientes);

        mnuFuncionários.setText("Funcionários");

        itmCadastrarFuncionario.setText("Cadastrar Funcionário");
        mnuFuncionários.add(itmCadastrarFuncionario);

        itmConsultarFuncionario.setText("Consultar Funcionário");
        itmConsultarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmConsultarFuncionarioActionPerformed(evt);
            }
        });
        mnuFuncionários.add(itmConsultarFuncionario);

        itmAlterarFuncionario.setText("Alterar Funcionário");
        mnuFuncionários.add(itmAlterarFuncionario);

        itmExcluirFuncionario.setText("Excluir Funcionários");
        mnuFuncionários.add(itmExcluirFuncionario);

        jMenuBar1.add(mnuFuncionários);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(646, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmConsultarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmConsultarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmConsultarFuncionarioActionPerformed

    private void itmConsultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmConsultarClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmConsultarClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlterarClientes;
    private javax.swing.JMenuItem itmAlterarFuncionario;
    private javax.swing.JMenuItem itmCadastrarFuncionario;
    private javax.swing.JMenuItem itmCancelarClientes;
    private javax.swing.JMenuItem itmConsultarClientes;
    private javax.swing.JMenuItem itmConsultarFuncionario;
    private javax.swing.JMenuItem itmExcluirFuncionario;
    private javax.swing.JMenuItem itmPagamentoClientes;
    private javax.swing.JMenuItem itmRelatóriosClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblFundo1;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuFuncionários;
    // End of variables declaration//GEN-END:variables
}
